require(tree)
require(randomForest)
require(caret)
require(e1071)iris <- iris
set.seed(1234)
High1=ifelse(iris$Sepal.Length<=5.843,"yes","no")
High2=ifelse(iris$Sepal.Width<=3.057,"yes","no")
High3=ifelse(iris$Petal.Length<=3.758,"yes","no")
High4=ifelse(iris$Petal.Width<=1.199,"yes","no")

iris1=data.frame(iris,High1)
iris2=data.frame(iris,High2)
iris3=data.frame(iris,High3)
iris4=data.frame(iris,High4)

training1=sample(1:nrow(iris1),100)
training2=sample(1:nrow(iris2),100)
training3=sample(1:nrow(iris3),100)
training4=sample(1:nrow(iris4),100)
training5=sample(1:nrow(iris),100)

tree.iris1=tree(High1~.-Sepal.Length, iris1, subset = training1)
tree.iris2=tree(High2~.-Sepal.Width, iris2, subset = training2)
tree.iris3=tree(High3~.-Petal.Length, iris3, subset = training3)
tree.iris4=tree(High4~.-Petal.Width, iris4, subset = training4)
tree.iris5=tree(Species~., iris, subset = training5)

tree.pred1 = predict(tree.iris1, iris1[-training1,], type="class")
tree.pred2 = predict(tree.iris2, iris2[-training2,], type="class")
tree.pred3 = predict(tree.iris3, iris3[-training3,], type="class")
tree.pred4 = predict(tree.iris4, iris4[-training4,], type="class")
tree.pred5 = predict(tree.iris5, iris[-training5,], type="class")

tab1 <- with(iris1[-training1,], table(tree.pred1, High1))
confusionMatrix(tab1)
tab2 <- with(iris2[-training2,], table(tree.pred2, High2))
confusionMatrix(tab2)
tab3 <- with(iris3[-training3,], table(tree.pred3, High3))
confusionMatrix(tab3)
tab4 <- with(iris4[-training4,], table(tree.pred4, High4))
confusionMatrix(tab4)
tab5 <- with(iris[-training5,], table(tree.pred5, Species))
confusionMatrix(tab5)